#!/usr/bin/env bash
set -euo pipefail

# Prefer Next.js local env; fall back to .env
if [ -f .env.local ]; then
    ENV_FILE=".env.local"
elif [ -f .env ]; then
    ENV_FILE=".env"
else
    echo "ERROR: No .env.local or .env found."
    exit 1
fi

TYPES_FILE="src/hooks/supabase.ts"
DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
DB_CONTAINER="supabase_db_proxima_landing"

# BSD sed (macOS) needs `sed -i ''`; GNU sed (Linux) wants `sed -i`
sed_inplace() {
    if sed --version >/dev/null 2>&1; then
        sed -i "$@"
    else
        sed -i '' "$@"
    fi
}

# Prefer host psql; fall back to container if missing
run_psql() {
    if command -v psql >/dev/null 2>&1; then
        psql "$DB_URL" "$@"
    else
        docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres "$@"
    fi
}

# ── 1. Init supabase project if no config.toml ──────────────────────────
if [ ! -f supabase/config.toml ]; then
    echo "==> No supabase/config.toml found, running supabase init..."
    npx supabase init
fi

# ── 2. Start local Supabase (idempotent - skips if already running) ─────
echo "==> Starting local Supabase..."
npx supabase start || true

# ── 3. Grab local connection details ────────────────────────────────────
LOCAL_STATUS=$(npx supabase status --output json 2>/dev/null || true)
LOCAL_URL=$(echo "$LOCAL_STATUS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('API_URL',''))" 2>/dev/null || true)
LOCAL_ANON_KEY=$(echo "$LOCAL_STATUS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('ANON_KEY',''))" 2>/dev/null || true)

if [ -z "$LOCAL_URL" ] || [ -z "$LOCAL_ANON_KEY" ]; then
    echo "ERROR: Could not read local Supabase URL/key from 'supabase status'."
    echo "Make sure Docker is running and try again."
    exit 1
fi

if ! command -v psql >/dev/null 2>&1; then
    if ! docker inspect "$DB_CONTAINER" >/dev/null 2>&1; then
        echo "ERROR: No host psql and DB container '$DB_CONTAINER' not found."
        echo "Install psql, or make sure local Supabase is running."
        exit 1
    fi
    echo "   psql:       docker exec ($DB_CONTAINER)"
else
    echo "   psql:       host"
fi

echo "   Env file:   $ENV_FILE"
echo "   Local URL:  $LOCAL_URL"
echo "   Anon key:   ${LOCAL_ANON_KEY:0:20}..."

# ── 4. Swap env file to point at local ─────────────────────────────────
if grep -q "^NEXT_PUBLIC_REACT_APP_SUPABASE_URL=https://" "$ENV_FILE"; then
    echo "==> Swapping $ENV_FILE to local Supabase..."

    # Comment out production values
    sed_inplace 's|^NEXT_PUBLIC_REACT_APP_SUPABASE_URL=https://|# PROD # NEXT_PUBLIC_REACT_APP_SUPABASE_URL=https://|' "$ENV_FILE"
    sed_inplace 's|^NEXT_PUBLIC_REACT_APP_SUPABASE_KEY=eyJ|# PROD # NEXT_PUBLIC_REACT_APP_SUPABASE_KEY=eyJ|' "$ENV_FILE"

    # Append local values
    cat >> "$ENV_FILE" <<EOF

# LOCAL SUPABASE (auto-generated by start-local-supabase.sh)
NEXT_PUBLIC_REACT_APP_SUPABASE_URL=${LOCAL_URL}
NEXT_PUBLIC_REACT_APP_SUPABASE_KEY=${LOCAL_ANON_KEY}
EOF
    echo "   $ENV_FILE updated. To revert, undo the '# PROD #' comments and remove the LOCAL block."
else
    echo "   $ENV_FILE already appears to use local (no https:// URL found). Skipping swap."
fi

# ── 5. Run migrations ──────────────────────────────────────────────────
echo "==> Running migrations..."
npx supabase migration up --local

# ── Restart Kong proxy (can get stale after db reset) ────────────────
docker restart supabase_kong_proxima_landing >/dev/null 2>&1 || true
sleep 3

# ── 7. Create test user + seed required rows ─────────────────────────
TEST_EMAIL="test@localhost.dev"
TEST_PASSWORD="Password123!"
TEST_FIRST_NAME="Test"
TEST_LAST_NAME="User"
TEST_USERNAME="test"

USER_EXISTS=$(run_psql -tAc "SELECT count(*) FROM auth.users WHERE email = '$TEST_EMAIL';" 2>/dev/null | tr -d '[:space:]' || echo "0")
USER_EXISTS="${USER_EXISTS:-0}"

if [ "$USER_EXISTS" -eq 0 ]; then
    echo "==> Creating test user ($TEST_EMAIL)..."

    # Sign up via auth API to get a proper JWT-capable user (retry - auth may still be starting)
    SIGNUP_RESULT=""
    for i in 1 2 3 4 5; do
        SIGNUP_RESULT=$(curl -s -X POST "${LOCAL_URL}/auth/v1/signup" \
            -H "apikey: ${LOCAL_ANON_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"${TEST_EMAIL}\",\"password\":\"${TEST_PASSWORD}\"}")
        if echo "$SIGNUP_RESULT" | python3 -c "import sys,json; sys.exit(0 if json.load(sys.stdin).get('user',{}).get('id') else 1)" 2>/dev/null; then
            break
        fi
        echo "   Auth not ready, retrying ($i/5)..."
        sleep 2
    done

    TEST_USER_ID=$(echo "$SIGNUP_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('user',{}).get('id',''))" 2>/dev/null || true)

    if [ -z "$TEST_USER_ID" ]; then
        echo "   WARNING: Could not create test user. Auth response: $SIGNUP_RESULT"
    else
        echo "   Created user: $TEST_USER_ID"
    fi
else
    TEST_USER_ID=$(run_psql -tAc "SELECT id FROM auth.users WHERE email = '$TEST_EMAIL' LIMIT 1;" | tr -d '[:space:]')
    echo "   Test user already exists ($TEST_USER_ID)."
fi

# Profile + usage (auth signup does not populate public.users locally -
# handle_new_user exists but has no trigger on auth.users)
if [ -n "${TEST_USER_ID:-}" ]; then
    run_psql -q -c "
INSERT INTO public.users (id, email, first_name, last_name, username, timezone, created_at)
VALUES (
    '$TEST_USER_ID',
    '$TEST_EMAIL',
    '$TEST_FIRST_NAME',
    '$TEST_LAST_NAME',
    '$TEST_USERNAME',
    'UTC',
    now()
)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    username = EXCLUDED.username,
    timezone = EXCLUDED.timezone;
"

    # period_start defaults to the current Usage period (1st of the month, UTC)
    run_psql -q -c "INSERT INTO public.feature_usage (user_id, monthly_exports_used, monthly_llm_requests) VALUES ('$TEST_USER_ID', 0, 0) ON CONFLICT (user_id, period_start) DO NOTHING;"


    sed_inplace "s|^NEXT_PUBLIC_TEST_USER_EMAILS=.*|NEXT_PUBLIC_TEST_USER_EMAILS=$TEST_EMAIL|" "$ENV_FILE"
    if grep -q '^TEST_USER_ID=' "$ENV_FILE"; then
        sed_inplace "s|^TEST_USER_ID=.*|TEST_USER_ID=$TEST_USER_ID|" "$ENV_FILE"
    else
        echo "TEST_USER_ID=$TEST_USER_ID" >> "$ENV_FILE"
    fi

    echo "   public.users profile: $TEST_FIRST_NAME $TEST_LAST_NAME (@$TEST_USERNAME)"
    echo "   Login: $TEST_EMAIL / $TEST_PASSWORD"
fi

# ── 8. Regenerate types ─────────────────────────────────────────────────
echo "==> Regenerating TypeScript types..."
{ echo "/* eslint-disable @typescript-eslint/naming-convention */"; npx supabase gen types --lang=typescript --local 2>/dev/null; } > "$TYPES_FILE"

echo ""
echo "Done. Local Supabase is running and types are regenerated."
echo "To stop:  npx supabase stop"
echo "To revert $ENV_FILE: remove the LOCAL block at the bottom and uncomment the '# PROD #' lines."
echo "Test login: $TEST_EMAIL / $TEST_PASSWORD"
